name: 'Select Xcode'
description: 'Select the active Xcode installation via xcode-select'

inputs:
  xcode-path:
    description: 'Path to the Xcode developer directory'
    default: '/Applications/Xcode.app/Contents/Developer'

runs:
  using: "composite"
  steps:
    - name: Select Xcode
      shell: bash
      run: sudo xcode-select -s ${{ inputs.xcode-path }}
