name: 'Setup Prerequisites'
description: 'Shared steps to prepare build environment'

runs:
  using: "composite"
  steps:
    - name: Free up space on GitHub runner
      if: runner.os == 'Linux'
      shell: bash
      run: |
        df -h
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        df -h

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        # Only save Gradle User Home state for builds on the 'master' branch.
        # Builds on other branches will only read existing entries from the cache.
        cache-read-only: ${{ github.ref != 'refs/heads/master' }}

        # Limit the size of the cache entry.
        # These directories contain instrumented/transformed dependency jars which can be reconstructed relatively quickly.
        gradle-home-cache-excludes: |
          caches/jars-9
          caches/transforms-3
