name: 'Setup Prerequisites'
description: 'Shared steps to prepare build environment'

runs:
  using: "composite"
  steps:
    - name: Free up space on GitHub runner
      if: runner.os == 'Linux'
      shell: bash
      run: |
        df -h
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        df -h

    - name: Install LLVM
      if: runner.os == 'macOS'
      shell: bash
      run: brew install llvm

    - name: Install Vulkan SDK
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $version = '1.4.357.0'
        $sdk = "C:\VulkanSDK\$version"
        $installer = "$env:RUNNER_TEMP\VulkanSDK-$version.exe"
        Invoke-WebRequest "https://sdk.lunarg.com/sdk/download/$version/windows/vulkan_sdk.exe?Human=true" -OutFile $installer
        Start-Process -Wait -FilePath $installer -ArgumentList '--accept-licenses', '--default-answer', '--confirm-command', 'install', 'com.lunarg.vulkan.arm64'
        "VULKAN_SDK=$sdk" >> $env:GITHUB_ENV
        "$sdk\Bin" >> $env:GITHUB_PATH

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        # Only save Gradle User Home state for builds on the 'master' branch.
        # Builds on other branches will only read existing entries from the cache.
        cache-read-only: ${{ github.ref != 'refs/heads/master' }}

        # Limit the size of the cache entry.
        # These directories contain instrumented/transformed dependency jars which can be reconstructed relatively quickly.
        gradle-home-cache-excludes: |
          caches/jars-9
          caches/transforms-3
