// Generated by delombok at Mon Aug 30 12:25:17 MSK 2021
package org.jetbrains.skija.shaper

import org.jetbrains.skija.impl.Library.Companion.staticLoad
import org.jetbrains.annotations.ApiStatus
import org.jetbrains.skija.impl.RefCnt
import org.jetbrains.skija.impl.Managed.CleanerThunk
import org.jetbrains.skija.paragraph.Shadow
import org.jetbrains.skija.paragraph.TextBox
import org.jetbrains.skija.paragraph.Affinity
import org.jetbrains.skija.ManagedString
import org.jetbrains.skija.paragraph.Paragraph
import org.jetbrains.skija.IRange
import org.jetbrains.skija.FontFeature
import org.jetbrains.skija.Typeface
import org.jetbrains.skija.paragraph.HeightMode
import org.jetbrains.skija.paragraph.StrutStyle
import org.jetbrains.skija.paragraph.BaselineMode
import org.jetbrains.skija.paragraph.RectWidthMode
import org.jetbrains.skija.paragraph.FontCollection
import org.jetbrains.skija.FontMgr
import org.jetbrains.skija.paragraph.ParagraphCache
import org.jetbrains.skija.paragraph.ParagraphStyle
import org.jetbrains.skija.paragraph.RectHeightMode
import org.jetbrains.skija.paragraph.DecorationStyle
import org.jetbrains.skija.paragraph.ParagraphBuilder
import org.jetbrains.skija.paragraph.PlaceholderStyle
import org.jetbrains.skija.paragraph.TextStyleAttribute
import org.jetbrains.skija.paragraph.DecorationLineStyle
import org.jetbrains.skija.paragraph.PlaceholderAlignment
import org.jetbrains.skija.paragraph.PositionWithAffinity
import org.jetbrains.skija.paragraph.TypefaceFontProvider
import org.jetbrains.skija.shaper.Shaper
import org.jetbrains.skija.TextBlob
import org.jetbrains.skija.shaper.FontRun
import org.jetbrains.skija.FourByteTag
import org.jetbrains.skija.shaper.LanguageRun
import org.jetbrains.skija.shaper.ShapingOptions
import org.jetbrains.skija.shaper.FontMgrRunIterator
import org.jetbrains.skija.shaper.IcuBidiRunIterator
import org.jetbrains.skija.shaper.ManagedRunIterator
import org.jetbrains.skija.shaper.HbIcuScriptRunIterator
import org.jetbrains.skija.shaper.TextBlobBuilderRunHandler
import org.jetbrains.annotations.ApiStatus.OverrideOnly
import org.jetbrains.skija.skottie.Animation
import org.jetbrains.skija.sksg.InvalidationController
import org.jetbrains.skija.skottie.RenderFlag
import org.jetbrains.skija.skottie.AnimationBuilder
import org.jetbrains.skija.skottie.AnimationBuilderFlag
import org.jetbrains.skija.Matrix33
import org.jetbrains.skija.svg.SVGDOM
import org.jetbrains.skija.svg.SVGSVG
import org.jetbrains.skija.svg.SVGTag
import org.jetbrains.skija.svg.SVGNode
import org.jetbrains.skija.WStream
import org.jetbrains.skija.svg.SVGCanvas
import org.jetbrains.skija.svg.SVGLength
import org.jetbrains.skija.svg.SVGLengthType
import org.jetbrains.skija.svg.SVGLengthUnit
import org.jetbrains.skija.svg.SVGLengthContext
import org.jetbrains.skija.svg.SVGPreserveAspectRatio
import org.jetbrains.skija.svg.SVGPreserveAspectRatioAlign
import org.jetbrains.skija.svg.SVGPreserveAspectRatioScale
import org.jetbrains.skija.ColorAlphaType
import org.jetbrains.skija.AnimationDisposalMode
import org.jetbrains.skija.BlendMode
import org.jetbrains.skija.IRect
import org.jetbrains.skija.AnimationFrameInfo
import org.jetbrains.skija.BackendRenderTarget
import org.jetbrains.skija.IHasImageInfo
import org.jetbrains.skija.ImageInfo
import org.jetbrains.skija.IPoint
import org.jetbrains.skija.PixelRef
import org.jetbrains.skija.Shader
import org.jetbrains.skija.FilterTileMode
import org.jetbrains.skija.SamplingMode
import org.jetbrains.skija.U16String
import org.jetbrains.skija.SurfaceProps
import org.jetbrains.skija.RRect
import org.jetbrains.skija.ClipMode
import org.jetbrains.skija.FilterMode
import org.jetbrains.skija.Picture
import org.jetbrains.skija.Matrix44
import org.jetbrains.skija.EncodedOrigin
import org.jetbrains.skija.EncodedImageFormat
import org.jetbrains.skija.Color4f
import org.jetbrains.skija.ColorChannel
import org.jetbrains.skija.ColorFilter
import org.jetbrains.skija.ColorMatrix
import org.jetbrains.skija.ColorFilter._LinearToSRGBGammaHolder
import org.jetbrains.skija.ColorFilter._SRGBToLinearGammaHolder
import org.jetbrains.skija.InversionMode
import org.jetbrains.skija.ColorFilter._LumaHolder
import org.jetbrains.skija.ColorInfo
import org.jetbrains.skija.ColorSpace._SRGBHolder
import org.jetbrains.skija.ColorSpace._SRGBLinearHolder
import org.jetbrains.skija.ColorSpace._DisplayP3Holder
import org.jetbrains.skija.ContentChangeMode
import org.jetbrains.skija.CubicResampler
import org.jetbrains.skija.DirectContext
import org.jetbrains.skija.GLBackendState
import org.jetbrains.annotations.ApiStatus.NonExtendable
import org.jetbrains.skija.FilterBlurMode
import org.jetbrains.skija.MipmapMode
import org.jetbrains.skija.FilterMipmap
import org.jetbrains.skija.FilterQuality
import org.jetbrains.skija.FontEdging
import org.jetbrains.skija.FontHinting
import org.jetbrains.skija.FontExtents
import org.jetbrains.skija.FontFamilyName
import org.jetbrains.skija.FontMgr._DefaultHolder
import org.jetbrains.skija.FontStyleSet
import org.jetbrains.skija.FontSlant
import org.jetbrains.skija.FontWidth
import org.jetbrains.skija.FontVariation
import org.jetbrains.skija.FontVariationAxis
import org.jetbrains.skija.GradientStyle
import org.jetbrains.skija.MaskFilter
import org.jetbrains.skija.OutputWStream
import org.jetbrains.skija.PaintMode
import org.jetbrains.skija.PaintStrokeCap
import org.jetbrains.skija.PaintStrokeJoin
import org.jetbrains.skija.PathEffect
import org.jetbrains.skija.PaintFilterCanvas
import org.jetbrains.skija.PathSegment
import org.jetbrains.skija.PathOp
import org.jetbrains.skija.PathFillMode
import org.jetbrains.skija.PathVerb
import org.jetbrains.skija.PathEllipseArc
import org.jetbrains.skija.PathDirection
import org.jetbrains.skija.PathSegmentIterator
import org.jetbrains.skija.RSXform
import org.jetbrains.skija.PathMeasure
import org.jetbrains.skija.PictureRecorder
import org.jetbrains.skija.PixelGeometry
import org.jetbrains.skija.Point3
import org.jetbrains.skija.RuntimeEffect
import org.jetbrains.skija.ShadowUtils
import org.jetbrains.skija.SurfaceOrigin
import org.jetbrains.skija.SurfaceColorFormat
import org.jetbrains.skija.TextBlobBuilder
import java.util.*

class ShapingOptions(
    @field:Internal val fontMgr: FontMgr?,
    @field:Internal val features: Array<FontFeature?>?,
    @field:Internal val isLeftToRight: Boolean,
    /**
     * If enabled, fallback font runs will not be broken by whitespace from original font
     */
    @field:Internal val isApproximateSpaces: Boolean,
    /**
     * If enabled, fallback font runs will not be broken by punctuation from original font
     */
    @field:Internal val isApproximatePunctuation: Boolean
) {

    /**
     * If enabled, fallback font runs will not be broken by whitespace from original font
     */
    /**
     * If enabled, fallback font runs will not be broken by punctuation from original font
     */
    fun withFeatures(features: Array<FontFeature?>?): ShapingOptions {
        return ShapingOptions(fontMgr, features, isLeftToRight, isApproximateSpaces, isApproximatePunctuation)
    }

    fun withFeatures(featuresString: String?): ShapingOptions {
        return if (featuresString == null) withFeatures(null as Array<FontFeature?>?) else withFeatures(
            FontFeature.Companion.parse(
                featuresString
            )
        )
    }

    override fun equals(o: Any?): Boolean {
        if (o === this) return true
        if (o !is ShapingOptions) return false
        val other = o
        if (!other.canEqual(this as Any)) return false
        if (isLeftToRight != other.isLeftToRight) return false
        if (isApproximateSpaces != other.isApproximateSpaces) return false
        if (isApproximatePunctuation != other.isApproximatePunctuation) return false
        val `this$_fontMgr`: Any? = fontMgr
        val `other$_fontMgr`: Any? = other.fontMgr
        if (if (`this$_fontMgr` == null) `other$_fontMgr` != null else `this$_fontMgr` != `other$_fontMgr`) return false
        return if (!Arrays.deepEquals(features, other.features)) false else true
    }

    protected fun canEqual(other: Any?): Boolean {
        return other is ShapingOptions
    }

    override fun hashCode(): Int {
        val PRIME = 59
        var result = 1
        result = result * PRIME + if (isLeftToRight) 79 else 97
        result = result * PRIME + if (isApproximateSpaces) 79 else 97
        result = result * PRIME + if (isApproximatePunctuation) 79 else 97
        val `$_fontMgr`: Any? = fontMgr
        result = result * PRIME + (`$_fontMgr`?.hashCode() ?: 43)
        result = result * PRIME + Arrays.deepHashCode(features)
        return result
    }

    override fun toString(): String {
        return "ShapingOptions(_fontMgr=" + fontMgr + ", _features=" + Arrays.deepToString(features) + ", _leftToRight=" + isLeftToRight + ", _approximateSpaces=" + isApproximateSpaces + ", _approximatePunctuation=" + isApproximatePunctuation + ")"
    }

    fun withFontMgr(_fontMgr: FontMgr?): ShapingOptions {
        return if (fontMgr === _fontMgr) this else ShapingOptions(
            _fontMgr,
            features,
            isLeftToRight,
            isApproximateSpaces,
            isApproximatePunctuation
        )
    }

    fun withLeftToRight(_leftToRight: Boolean): ShapingOptions {
        return if (isLeftToRight == _leftToRight) this else ShapingOptions(
            fontMgr,
            features,
            _leftToRight,
            isApproximateSpaces,
            isApproximatePunctuation
        )
    }

    /**
     * If enabled, fallback font runs will not be broken by whitespace from original font
     * @return `this`.
     */
    fun withApproximateSpaces(_approximateSpaces: Boolean): ShapingOptions {
        return if (isApproximateSpaces == _approximateSpaces) this else ShapingOptions(
            fontMgr,
            features,
            isLeftToRight,
            _approximateSpaces,
            isApproximatePunctuation
        )
    }

    /**
     * If enabled, fallback font runs will not be broken by punctuation from original font
     * @return `this`.
     */
    fun withApproximatePunctuation(_approximatePunctuation: Boolean): ShapingOptions {
        return if (isApproximatePunctuation == _approximatePunctuation) this else ShapingOptions(
            fontMgr,
            features,
            isLeftToRight,
            isApproximateSpaces,
            _approximatePunctuation
        )
    }

    companion object {
        val DEFAULT = ShapingOptions(null, null, true, true, true)
    }
}