/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jetbrains_awthrl_Components_Window */

#ifndef _Included_org_jetbrains_awthrl_Components_Window
#define _Included_org_jetbrains_awthrl_Components_Window
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jetbrains_awthrl_Components_Window_FOCUS_TRAVERSABLE_UNKNOWN
#define org_jetbrains_awthrl_Components_Window_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef org_jetbrains_awthrl_Components_Window_FOCUS_TRAVERSABLE_DEFAULT
#define org_jetbrains_awthrl_Components_Window_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef org_jetbrains_awthrl_Components_Window_FOCUS_TRAVERSABLE_SET
#define org_jetbrains_awthrl_Components_Window_FOCUS_TRAVERSABLE_SET 2L
#undef org_jetbrains_awthrl_Components_Window_TOP_ALIGNMENT
#define org_jetbrains_awthrl_Components_Window_TOP_ALIGNMENT 0.0f
#undef org_jetbrains_awthrl_Components_Window_CENTER_ALIGNMENT
#define org_jetbrains_awthrl_Components_Window_CENTER_ALIGNMENT 0.5f
#undef org_jetbrains_awthrl_Components_Window_BOTTOM_ALIGNMENT
#define org_jetbrains_awthrl_Components_Window_BOTTOM_ALIGNMENT 1.0f
#undef org_jetbrains_awthrl_Components_Window_LEFT_ALIGNMENT
#define org_jetbrains_awthrl_Components_Window_LEFT_ALIGNMENT 0.0f
#undef org_jetbrains_awthrl_Components_Window_RIGHT_ALIGNMENT
#define org_jetbrains_awthrl_Components_Window_RIGHT_ALIGNMENT 1.0f
#undef org_jetbrains_awthrl_Components_Window_serialVersionUID
#define org_jetbrains_awthrl_Components_Window_serialVersionUID -7644114512714619750LL
#undef org_jetbrains_awthrl_Components_Window_serialVersionUID
#define org_jetbrains_awthrl_Components_Window_serialVersionUID 4613797578919906343LL
#undef org_jetbrains_awthrl_Components_Window_INCLUDE_SELF
#define org_jetbrains_awthrl_Components_Window_INCLUDE_SELF 1L
#undef org_jetbrains_awthrl_Components_Window_SEARCH_HEAVYWEIGHTS
#define org_jetbrains_awthrl_Components_Window_SEARCH_HEAVYWEIGHTS 1L
#undef org_jetbrains_awthrl_Components_Window_OPENED
#define org_jetbrains_awthrl_Components_Window_OPENED 1L
#undef org_jetbrains_awthrl_Components_Window_serialVersionUID
#define org_jetbrains_awthrl_Components_Window_serialVersionUID 4497834738069338734LL
#undef org_jetbrains_awthrl_Components_Window_DEFAULT_CURSOR
#define org_jetbrains_awthrl_Components_Window_DEFAULT_CURSOR 0L
#undef org_jetbrains_awthrl_Components_Window_CROSSHAIR_CURSOR
#define org_jetbrains_awthrl_Components_Window_CROSSHAIR_CURSOR 1L
#undef org_jetbrains_awthrl_Components_Window_TEXT_CURSOR
#define org_jetbrains_awthrl_Components_Window_TEXT_CURSOR 2L
#undef org_jetbrains_awthrl_Components_Window_WAIT_CURSOR
#define org_jetbrains_awthrl_Components_Window_WAIT_CURSOR 3L
#undef org_jetbrains_awthrl_Components_Window_SW_RESIZE_CURSOR
#define org_jetbrains_awthrl_Components_Window_SW_RESIZE_CURSOR 4L
#undef org_jetbrains_awthrl_Components_Window_SE_RESIZE_CURSOR
#define org_jetbrains_awthrl_Components_Window_SE_RESIZE_CURSOR 5L
#undef org_jetbrains_awthrl_Components_Window_NW_RESIZE_CURSOR
#define org_jetbrains_awthrl_Components_Window_NW_RESIZE_CURSOR 6L
#undef org_jetbrains_awthrl_Components_Window_NE_RESIZE_CURSOR
#define org_jetbrains_awthrl_Components_Window_NE_RESIZE_CURSOR 7L
#undef org_jetbrains_awthrl_Components_Window_N_RESIZE_CURSOR
#define org_jetbrains_awthrl_Components_Window_N_RESIZE_CURSOR 8L
#undef org_jetbrains_awthrl_Components_Window_S_RESIZE_CURSOR
#define org_jetbrains_awthrl_Components_Window_S_RESIZE_CURSOR 9L
#undef org_jetbrains_awthrl_Components_Window_W_RESIZE_CURSOR
#define org_jetbrains_awthrl_Components_Window_W_RESIZE_CURSOR 10L
#undef org_jetbrains_awthrl_Components_Window_E_RESIZE_CURSOR
#define org_jetbrains_awthrl_Components_Window_E_RESIZE_CURSOR 11L
#undef org_jetbrains_awthrl_Components_Window_HAND_CURSOR
#define org_jetbrains_awthrl_Components_Window_HAND_CURSOR 12L
#undef org_jetbrains_awthrl_Components_Window_MOVE_CURSOR
#define org_jetbrains_awthrl_Components_Window_MOVE_CURSOR 13L
#undef org_jetbrains_awthrl_Components_Window_NORMAL
#define org_jetbrains_awthrl_Components_Window_NORMAL 0L
#undef org_jetbrains_awthrl_Components_Window_ICONIFIED
#define org_jetbrains_awthrl_Components_Window_ICONIFIED 1L
#undef org_jetbrains_awthrl_Components_Window_MAXIMIZED_HORIZ
#define org_jetbrains_awthrl_Components_Window_MAXIMIZED_HORIZ 2L
#undef org_jetbrains_awthrl_Components_Window_MAXIMIZED_VERT
#define org_jetbrains_awthrl_Components_Window_MAXIMIZED_VERT 4L
#undef org_jetbrains_awthrl_Components_Window_MAXIMIZED_BOTH
#define org_jetbrains_awthrl_Components_Window_MAXIMIZED_BOTH 6L
#undef org_jetbrains_awthrl_Components_Window_serialVersionUID
#define org_jetbrains_awthrl_Components_Window_serialVersionUID 2673458971256075116LL
	/*
	 * Class:     org_jetbrains_awthrl_Components_Window
	 * Method:    redraw
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_org_jetbrains_awthrl_Components_Window_redrawLayer
	(JNIEnv *, jobject);

	/*
	 * Class:     org_jetbrains_awthrl_Components_Window
	 * Method:    updateLayer
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_org_jetbrains_awthrl_Components_Window_updateLayer
	(JNIEnv *, jobject);

	/*
	 * Class:     org_jetbrains_awthrl_Components_Window
	 * Method:    dispose
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_org_jetbrains_awthrl_Components_Window_disposeLayer
	(JNIEnv *, jobject);

	/*
	 * Class:     org_jetbrains_awthrl_Components_Window
	 * Method:    getContentScale
	 * Signature: ()V
	 */
	JNIEXPORT jfloat JNICALL Java_org_jetbrains_awthrl_Components_Window_getContentScale
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
