/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jetbrains_awthrl_Components_HardwareLayer */

#ifndef _Included_org_jetbrains_awthrl_Components_HardwareLayer
#define _Included_org_jetbrains_awthrl_Components_HardwareLayer
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jetbrains_awthrl_Components_HardwareLayer_FOCUS_TRAVERSABLE_UNKNOWN
#define org_jetbrains_awthrl_Components_HardwareLayer_FOCUS_TRAVERSABLE_UNKNOWN \
  0L
#undef org_jetbrains_awthrl_Components_HardwareLayer_FOCUS_TRAVERSABLE_DEFAULT
#define org_jetbrains_awthrl_Components_HardwareLayer_FOCUS_TRAVERSABLE_DEFAULT \
  1L
#undef org_jetbrains_awthrl_Components_HardwareLayer_FOCUS_TRAVERSABLE_SET
#define org_jetbrains_awthrl_Components_HardwareLayer_FOCUS_TRAVERSABLE_SET 2L
#undef org_jetbrains_awthrl_Components_HardwareLayer_TOP_ALIGNMENT
#define org_jetbrains_awthrl_Components_HardwareLayer_TOP_ALIGNMENT 0.0f
#undef org_jetbrains_awthrl_Components_HardwareLayer_CENTER_ALIGNMENT
#define org_jetbrains_awthrl_Components_HardwareLayer_CENTER_ALIGNMENT 0.5f
#undef org_jetbrains_awthrl_Components_HardwareLayer_BOTTOM_ALIGNMENT
#define org_jetbrains_awthrl_Components_HardwareLayer_BOTTOM_ALIGNMENT 1.0f
#undef org_jetbrains_awthrl_Components_HardwareLayer_LEFT_ALIGNMENT
#define org_jetbrains_awthrl_Components_HardwareLayer_LEFT_ALIGNMENT 0.0f
#undef org_jetbrains_awthrl_Components_HardwareLayer_RIGHT_ALIGNMENT
#define org_jetbrains_awthrl_Components_HardwareLayer_RIGHT_ALIGNMENT 1.0f
#undef org_jetbrains_awthrl_Components_HardwareLayer_serialVersionUID
#define org_jetbrains_awthrl_Components_HardwareLayer_serialVersionUID         \
  -7644114512714619750LL
#undef org_jetbrains_awthrl_Components_HardwareLayer_serialVersionUID
#define org_jetbrains_awthrl_Components_HardwareLayer_serialVersionUID         \
  -2284879212465893870LL
/*
 * Class:     org_jetbrains_awthrl_Components_HardwareLayer
 * Method:    redrawLayer
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_org_jetbrains_awthrl_Components_HardwareLayer_redrawLayer(JNIEnv *,
                                                               jobject);

/*
 * Class:     org_jetbrains_awthrl_Components_HardwareLayer
 * Method:    updateLayer
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_org_jetbrains_awthrl_Components_HardwareLayer_updateLayer(JNIEnv *,
                                                               jobject);

/*
 * Class:     org_jetbrains_awthrl_Components_HardwareLayer
 * Method:    disposeLayer
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_org_jetbrains_awthrl_Components_HardwareLayer_disposeLayer(JNIEnv *,
                                                                jobject);

/*
 * Class:     org_jetbrains_awthrl_Components_HardwareLayer
 * Method:    getContentScale
 * Signature: ()V
 */
JNIEXPORT jfloat JNICALL
Java_org_jetbrains_awthrl_Components_HardwareLayer_getContentScale(JNIEnv *,
                                                                   jobject);

#ifdef __cplusplus
}
#endif
#endif
