import org.gradle.api.artifacts.Configuration
import org.gradle.api.component.AdhocComponentWithVariants
import org.jetbrains.kotlin.gradle.plugin.KotlinTarget

/**
 * Adds an extra Gradle variant to the software component of a Kotlin target.
 *
 * KGP creates one [org.jetbrains.kotlin.gradle.plugin.mpp.KotlinTargetSoftwareComponentImpl]
 * per target and wires it into the Maven publication generated by the Kotlin plugin.
 * That component wraps an internal [AdhocComponentWithVariants]; adding a variant to it
 * makes the variant appear in the generated Gradle Module Metadata (.module file) and
 * therefore reachable via [org.gradle.api.artifacts.ArtifactView] with
 * [org.gradle.api.artifacts.ArtifactView.ViewConfiguration.withVariantReselection].
 *
 * The variant is NOT mapped to any Maven scope, so it does not produce a <dependency>
 * entry in the pom.xml — only Gradle-aware consumers can resolve it.
 *
 * Implementation note: [org.jetbrains.kotlin.gradle.plugin.mpp.KotlinTargetSoftwareComponentImpl]
 * is `internal` to KGP and its `adhocComponent` field is `private`, hence the suppression
 * and reflection. Verified against KGP sources in:
 *   libraries/tools/kotlin-gradle-plugin/src/common/kotlin/org/jetbrains/kotlin/gradle/plugin/mpp/
 *     KotlinTargetSoftwareComponentImpl.kt
 *     AbstractKotlinTarget.kt
 */
@Suppress("INVISIBLE_REFERENCE", "INVISIBLE_MEMBER")
fun addVariantToKotlinTarget(target: KotlinTarget, configuration: Configuration) {
    val component = target.components
        .filterIsInstance<org.jetbrains.kotlin.gradle.plugin.mpp.KotlinTargetSoftwareComponentImpl>()
        .single()

    val adhocField = component.javaClass.getDeclaredField("adhocComponent")
    adhocField.isAccessible = true
    val adhocComponent = adhocField.get(component) as AdhocComponentWithVariants

    // No mapToMavenScope call — the variant appears only in Gradle Module Metadata,
    // not in the pom.xml dependency list.
    adhocComponent.addVariantsFromConfiguration(configuration) {}
}
