import internal.utils.ArgBuilder
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputDirectory

abstract class OptimizeSkikoWasmTask : AbstractSkikoNativeToolTask() {

    @get:Input
    abstract val flags: ListProperty<String>

    @get:Input
    abstract val optimizer: Property<String>

    @get:InputDirectory
    abstract val inputDir: DirectoryProperty

    @get:Input
    abstract val libOutputFileName: Property<String>

    override val outDirNameForTool: String
        get() = "optimize"

    override fun execute(mode: ToolMode, args: ArgBuilder) {
        check(mode is ToolMode.NonIncremental) {
            "Optimization is not incremental, but $mode is received"
        }

        val inputDirectory = inputDir.get().asFile
        val outputDirectory = outDir.get().asFile
        outputDirectory.mkdirs()

        inputDirectory.walkTopDown()
            .filter { it.isFile }
            .forEach { inputFile ->
                val outputFile = outputDirectory.resolve("${libOutputFileName.get()}.${inputFile.extension}")

                when (inputFile.extension) {
                    "wasm" -> {
                        val optimizeArgs = createArgBuilder().apply {
                            arg(value = inputFile)
                            rawArgs(flags.get())
                            arg("-o", outputFile)
                        }

                        logArgs("Optimize args for ${inputFile.name}", optimizeArgs)

                        execOperations.exec {
                            executable = optimizer.get()
                            workingDir = outputDirectory
                            this.args = optimizeArgs.toArray().toList()
                        }
                    }
                    "mjs" -> {
                        // *.mjs files are not really optimized, but they refer to the paired
                        // *.wasm file generated by emcc. Keep that reference in sync with the
                        // optimized wasm output name.
                        outputFile.writeText(
                            inputFile.readText()
                                .replace(
                                    "${inputFile.nameWithoutExtension}.wasm",
                                    "${libOutputFileName.get()}.wasm"
                                )
                        )
                    }
                }
            }
    }

}
