name: 'Docker Publish'
description: 'Build and optionally publish a Docker image to a registry'

inputs:
  registry:
    description: 'Docker registry (e.g., ghcr.io)'
    required: true
  namespace:
    description: 'Image namespace (e.g., owner/repo)'
    required: true
  image_name:
    description: 'Image name (e.g., linux-amd64)'
    required: true
  context:
    description: 'Build context path (e.g., ./skiko/docker/linux-amd64)'
    required: true
  platforms:
    description: 'Target platforms (e.g., linux/amd64 or linux/amd64,linux/arm64)'
    required: true
  tag:
    description: 'Image tag (e.g., ubuntu-2004)'
    required: true
  should_publish:
    description: 'Whether to push the image to the registry'
    required: true
  github_token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Set up Docker Buildx'
      uses: docker/setup-buildx-action@v3

    - name: 'Log into registry'
      if: inputs.should_publish == 'true'
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: 'Extract metadata'
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.namespace }}/${{ inputs.image_name }}
        tags: |
          type=raw,value=${{ inputs.tag }}

    - name: 'Build and push'
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.should_publish == 'true' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
